CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    status TEXT DEFAULT 'ပေါင်းရန်',
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE DEFAULT CURRENT_DATE,
    description TEXT,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    amount NUMERIC DEFAULT 0,
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow authenticated categories select" ON public.categories;
DROP POLICY IF EXISTS "Allow authenticated categories insert" ON public.categories;
DROP POLICY IF EXISTS "Allow authenticated categories update" ON public.categories;
DROP POLICY IF EXISTS "Allow authenticated categories delete" ON public.categories;
DROP POLICY IF EXISTS "Allow authenticated items select" ON public.items;
DROP POLICY IF EXISTS "Allow authenticated items insert" ON public.items;
DROP POLICY IF EXISTS "Allow authenticated items update" ON public.items;
DROP POLICY IF EXISTS "Allow authenticated items delete" ON public.items;

CREATE POLICY "Allow authenticated categories select" ON public.categories FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated categories insert" ON public.categories FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated categories update" ON public.categories FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Allow authenticated categories delete" ON public.categories FOR DELETE TO authenticated USING (true);

CREATE POLICY "Allow authenticated items select" ON public.items FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated items insert" ON public.items FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated items update" ON public.items FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Allow authenticated items delete" ON public.items FOR DELETE TO authenticated USING (true);